### ISSUE TITLE
Update YAML -> RST process to support different sets of elements

### ISSUE THREAD

**Issue by sduckett** [votinginfoproject/vip-specification#324] opened 2016-06-30 15:54 UTC
The [current rendering process](https://github.com/votinginfoproject/vip-specification/blob/vip52/CONTRIBUTING.md#updating-the-documentation) makes the assumption that we have the same set of elements for both XML and CSV versions of the feed. With the changes to version 5.1 of the spec, the CSV feeds have diverged a bit, and we can't have the same set of elements in the documentation; for example, `BallotSelectionBase` will be folded in with `BallotSelection` in a CSV version of the feed.

We need to change the way YAML is rendered to RST; we can't use all of the elements all of the time. I'd propose moving the contents of `docs/yaml` into `docs/yaml/xml` and placing the CSV specific examples in `docs/yaml/csv`.

**Comment by jdmgoogle** [comment] 2016-06-30 16:02
I'm worried that a drastic separation of the XML and CSV source documentation would lead to significant unintended drift between documentation (i.e., the CSV documentation would end up lagging behind XML documentation for even common elements).

Also, I'm slightly confused by your example. `BallotSelectionBase` is the type of an object, and `BallotSelection` is the name of that object within the `VipObject`. There is no `BallotSelection` type.

**Comment by MariaBianchi** [comment] 2016-06-30 16:30
Ignoring the example for now, I wanted to create separate CSV documentation because the way the documentation is currently set up, where the CSV documentation pulls the tables for the related XML object, is going to cause confusion when states attempt to create the CSVs. Though in general they mirror each other, the structure of the CSVs is different enough that those tables imperfectly represent what needs to be in the CSVs. As we're trying to move states to 5.1, which some are finding a little daunting, I want to remove as much friction as I possibly can. 

You're correct, it does require any updates to the documentation to be made to both branches, and in that respect this solution isn't ideal, but I think increasing the ease of adoption will ultimately make it worthwhile.

**Comment by jdmgoogle** [comment] 2016-06-30 17:44
Understood. Could you help me understand some of the specific differences between the XML object/element organization and what the CSV input files/columns will look like?

If we can find some way to minimize duplication (e.g., through some flags or options in the YAML files) we could generate CSV-specific documentation while minimizing the odds that the documentation for common elements would diverge.

**Comment by MariaBianchi** [comment] 2016-06-30 19:42
Very quickly, I wanted to ask - what sort of updates to the XML documentation do you forsee that would cause this drift? 

The differences are primarily in where things are housed. To find the information you'd want to populate [ballot_measure_contest.txt](https://github.com/votinginfoproject/csv-templates/blob/master/vip_5.1_csv_templates/ballot_measure_contest.txt), you need to look at the XML documentation pages for BallotMeasureContest, ContestBase and External Identifier. 

The CSVs also cap repeating for some fields, and don't support internationalized text.

The full template set for all of the files are [here](https://github.com/votinginfoproject/csv-templates/tree/master/vip_5.1_csv_templates).

**Comment by cjerdonek** [comment] 2016-06-30 19:50
Hi, @jdmgoogle is right. I think the best way to approach this would be to
take a few representative examples of CSV elements and what you want the
documentation for those to look like as compared with the XML. Then, work
backwards to find a way to represent that in the YAML that minimizes
duplication with the XML (or to say another way, maximizes the overlap). I
would also highly encourage keeping the CSV and XML-specific data as close
to each other as possible (ideally in the same file). That way, it will be
that much easier to remember to update both formats in cases where the
underlying data is "non-overlapping."

**Comment by cjerdonek** [comment] 2016-06-30 19:56
Any time either format would need to be updated is a time liable to cause
drift / outdated documentation -- if the source data is maintained
separately. The CSV docs were never really brought into the YAML format
because the "requirements" weren't known (i.e. what people want the CSV
docs to look like vis a vis the XML). I believe I asked on GitHub several
months back, but the discussion never really got off the ground.

**Comment by MariaBianchi** [comment] 2016-07-05 16:05
My concern about updates is that the actual 5.1 CSV specification itself can't change, since it needs to fit this particular format in order for us to process it into XML. (I'd rather it drift the the XML documentation than from the CSV parsing tools.)

If by updates to the documentation you mean cosmetic changes, that's fine, but if you'd expect it to be more significant, then separate sources may serve our purposes better.

**Comment by jdmgoogle** [comment] 2016-07-11 16:22
@MariaBianchi Thank you for the examples. It sounds like the main differences between the XML and CSV documentation and elements are:

1. CSV files have headers which reference both that object and its parent object (e.g., the CSV for a  `CandidateContest` includes not just `CandidateContest` but also `ContestBase` headers);
2. CSV files don't support `InternationalizedText`; and
3. CSV files don't support repeating fields in any (most?) cases.

If this is true, would a reasonable set of changes to the YAML and the documentation-generating script be:

1. Update the YAML files to include an `extends` field so we explicitly flag that the given element extends the referenced class;
2. Update the script to include inline the elements from the class being extended (e.g., the `CandidateContest` CSV documentation would include the `ContestBase` documentation inline);
3. Include a `csv-type` field in the YAML files so we can handle the "CSVs don't support `InternationalizedText`" situation;
4. Update the script to never mark a field as "repeating" in the CSV documentation; and
5. Include a field `csv-header-name` for each element, to explicitly indicate what the CSV header is for a field.

Would this make it possible to generate correct and complete CSV documentation while maintaining the single YAML source for both sets of documentation? Or are there additional use cases which I haven't captured here?

**Comment by MariaBianchi** [comment] 2016-07-25 14:34
Sorry for the long delay. Yes, I think this would cover the use cases I'm trying to serve.

**Comment by MariaBianchi** [comment] 2016-08-04 14:28
@jdmgoogle While I think this is an a good way to handle the documentation, it's not one we have the time to implement right now. In the mean time, do you know if it's possible to take down the CSV documentation from read the docs?

**Comment by afsmythe** [comment] 2016-08-17 18:25
Hi. @MariaBianchi and I are hoping to make some effort in the short term with providing updated CSV documentation to users, giving those states updating their processes to 5.1 for the General Election a considerable amount of lead time to review the CSV requirements. I have done some review of the current 5.1 specification files to identify how the CSV specification can be incorporated in to the YAML/RST per @jdmgoogle bullet points. 

I am in agreement that there should be a single source for both CSV and XML specification items, and would like to update a small sample of YAML files with the `<extends>` `csv-type>` and `<csc-header-name>` mentioned above in order to give an idea of the amount of work required to incorporate the whole CSV specification in to the YAML files. 

That said, @jdmgoogle would you mind providing a bit more technical detail of how the `<extends>` `csv-type>` and `<csc-header-name>` would be implemented in the YAML?

Also, what is the general consensus for the amount of work required to update the `<norm_yaml>` and `<make_rest>` scripts in order to incorporate these changes to the YAML files?

Thanks for your input, all. I am looking forward to contributing to the VIP project. 

Best,
Franklin
Data Lead | Voting Information Project
Democracy Works

**Comment by jdmgoogle** [comment] 2016-08-23 20:17
![Yay ... wait](http://cdn5.viralscape.com/wp-content/uploads/2014/04/Michael-Phelps-mom.gif)

**Comment by afsmythe** [comment] 2016-09-06 18:48
Hi, @jdmgoogle. I wanted to check in to see if you had any additional ideas about the best method of updating the VIP 5.1 specification materials to encompass both the XML and more user friendly CSV specific elements. I have put together a spreadsheet mapping each of the CSV object columns with the relevant XML element. I would be happy to make this spreadsheet available and also create additional documentation to assist with this effort. Just let me know what you think would be useful. 

I know you have already provided a summary of what updates could be made. Could you provide a estimate of the time required there? And perhaps also provide a quick example of how you think those solutions will be implemented, including the example YAML fields, python code, and reST updates?

Thanks so much for your time!

**Comment by jdmgoogle** [comment] 2016-09-07 13:44
@afsmythe I looked over this a bit more, and I think I see where there was some miscommunication. The CSV documentation from @nomadaisy and @MariaBianchi et. al is using some of the documentation generated by the Python scripts, but not all of it. Unfortunately we don't have the cycles to change the code and the documentation, but here's a high-level overview of the work that'll need to be done:

**Configuration Changes**

1. Update the YAML files to include an `extends` field so we explicitly flag that the given element extends the referenced class;
2. Include a `csv-type` field in the YAML files so we can handle the "CSVs don't support InternationalizedText" situation; and
3. Include a field `csv-header-name` for each element, to explicitly indicate what the CSV header is for a field.

**Code Changes**

1. In vippy/common.py give the `extends`, `csv-type`, and `csv-header-name` fields TAG_KEY_ constants (similar to TAG_KEY_NAME, TAG_KEY_TYPE, etc).
2. In vippy/rest.py
  1. separate out ELEMENT_COLUMNS into XML_ELEMENT_COLUMNS and CSV_ELEMENT_COLUMNS, and only include columns you want to see in the CSV documentation.
  2. include inline the elements from the class being extended (e.g., the CandidateContest CSV documentation would include the ContestBase documentation inline).
  3. generate single-csv and multi-csv files similar to how there are single-xml and multi-xml files.
3. Back in vippy/common.py, create separate rest_path functions for CSV and XML documentation.

There will be some other code changes, but the gist of it is that we'll move from having common RST files created to be shared by the CSV and XML documentation, and towards having the YAML files be the One True Source of information, and have the scripts create similar-but-nearly-identical RST outputs for XML and CSV documentation, based on the data contained in the YAML files.

As I said, on the Google end we don't have time to make these code changes, but we're more than happy to review PRs from Pew, DW, or even a third-party. The documentation code was actually written by a third-party contributor, @cjerdonek, so we're coming at the code from the same level of (un)familiarity as anyone else.

Let me know if you have any other questions.

**Comment by cjerdonek** [comment] 2016-09-09 20:17
Hi, @jdmgoogle gave a good summary of the types of things that would need to be added or modified to add CSV support. I'd be happy to help out here as time permits. My recommendation would be to start adding the necessary pieces incrementally so it's not a "giant" change added all at once. This would also let you see how things are evolving and would let you adjust what needs to be added once the work starts and you can see it take shape.

I could try to find some time to start some of this.

**Comment by afsmythe** [comment] 2016-09-16 19:52
Hi, @cjerdonek. I have completed some mapping of the 5.1 CSV objects to their relevant XML element and would like to offer a single example here for discussion and implementation. Hopefully this will assist with making changes to the YAML and reST files incrementally as we hope to do. 

The `candidate_contest.txt` object references the `CandidateContest` XML, which extends to the `ContestBase` and `ExternalIdentifiers` XML objects. The first column contains the CSV headers. Beginning with column 2 onward are the matching XML objects. 

`candidate_contest.txt` | `CandidateContest` | extends `ContestBase` | extends `ExternalIdentifiers`
--- | --- | --- | --- 
abbreviation | | Abbreviation | |
candidate_selection_ids | | CandidateSelection |
ballot_sub_title | | BallotSubTitle |
ballot_title | | BallotTitle |
electoral_district_id | | ElectoralDistrictId |
electorate_specification | | ElectorateSpecification |
external_identifier_type | ||IdentifierType
external_identifier_othertype |||OtherType
external_identifier_value |||Value
has_rotation | |HasRotation|
name | |Name|
sequence_order ||SequenceOrder|
vote_variation ||VoteVariation|
other_vote_variation ||OtherVoteVariation|
number_elected | NumberElected |
office_ids | OfficeIds |
primary_party_ids | PrimaryPartyIds | 
votes_allowed | VotesAllowed |
id |

If I can provide any additional information or materials please let me know.

**Comment by cjerdonek** [comment] 2016-09-16 21:39
Thanks, @afsmythe. I'll let you know if anything else would be helpful.

**Comment by afsmythe** [comment] 2016-12-06 21:23
As the dust around the election has settled some review of the 5.1 CSV specification and the states' efforts to conform to the specification has been made. I plan to get all updates to the CSV specification applied within the documentation soon and will take that opportunity to update the docs per some suggestions we have received from the states. 

This ongoing thread has been useful in highlighting the complexity of updating the documentation build process to serve both XML and CSV specifications from a single, common set of YAML files. I don't believe we are quite to a point where we can update the YAML/reST/HTML build process to that end, however there may be a quick win for us to easily update the CSV resources and provide more meaningful documentation to the states. 

I would like to propose we update the CSV template files which currently live [here](https://github.com/votinginfoproject/csv-templates/tree/master/vip_5.1_csv_templates) to include two comma separated items; the VIP csv column element and a description column.

One of the findings of the 5.1 states' usage of the github documentation was that the users were pointing almost exclusively to [the CSV Template files](https://github.com/votinginfoproject/csv-templates/tree/master/vip_5.1_csv_templates) for 5.1 CSV information. These files are stored separate of the [5.1 CSV Read the Docs](http://vip-specification.readthedocs.io/en/vip5/csv/index.html) and are not referenced there. We should be able to reference the CSV template files (to include an additional 'Description' column) from within the descriptive Read the Docs CSV documentation (replacing the XML table presently displayed) and hopefully steer the states' users there, away from the somewhat lacking CSV templates [here](https://github.com/votinginfoproject/csv-templates/tree/master/vip_5.1_csv_templates).

I believe the tasks would be:
- update the CSV template files, adding the additional Description column and providing detail about each CSV element.
- Create a template_files folder within the */docs/csv/ directory and copy the template files there
- Reference the updated CSV template files within the .rst files in */docs/csv/element_files/ using the `csv-table` RST directive, removing the current reference to the XML rst file. 

Thanks for your review! I am curious to hear anyone's thoughts on this option.

**Comment by jdmgoogle** [comment] 2017-01-11 15:41
@afsmythe Thanks for bringing the template files to our attention as needing more love.

I'm a bit hazy on what the "VIP csv column element" and "description" columns would be in practice. Could you provide an example of what a modified template file would look like, and maybe one or two data rows for a file that is based on the modified template?

Overall I do like the idea of migrating the CSV documentation and templates to be unified, and referencing the template files from the documentation.

**Comment by afsmythe** [comment] 2017-01-12 16:19
Sure, @jdmgoogle. I made a quick mock on my machine. Below are some notes and  a screenshot of what the ballot_measure_contest.txt documentation will look like once it includes the 'Description' column. 

Format columns to rows and add the description column to `ballot_measure_contest.txt` in a newly created */docs/csv/template_files/ directory:

```
abbreviation,An abbreviation for the Ballot Contest
ballot_measure_selection_ids,References the relevant selection object
ballot_sub_title,Subtitle of the Ballot item
ballot_title,Title of the Ballot item
electoral_district_id,References the relevant electoral district
electorate_specification,
external_identifier_type,
external_identifier_othertype,
external_identifier_value,
has_rotation,
name,
sequence_order,
vote_variation,
other_vote_variation,
con_statement,
effect_of_abstain,
full_text,
info_uri,
passage_threshold,
pro_statement,
summary_text,
type,
other_type,
id
```

The Description column is included within the docs by manually editing `*/docs/csv/element_files/ballot_measure_contest.rst` to reference the edited ballot_measure_contest.txt with:

```
.. csv-table:: ballot_measure_contest
	:file: ../../csv/template_files/ballot_measure_contest.txt
	:header: "CSV Element", "Description"
```

Following the tasks outlined https://github.com/votinginfoproject/vip-specification/blob/vip52/CONTRIBUTING.md#building-the-documentation builds the 'Description' edits in to the HTML. 

![screen shot 2017-01-12 at 11 10 14 am](https://cloud.githubusercontent.com/assets/16374798/21897606/227c03bc-d8b8-11e6-9409-b042fe1797e2.png)

NOTE: the CSV example_file included at the bottom of the screen will also need updating to match the VIP accurate template_file.

**Comment by jdmgoogle** [comment] 2017-01-12 16:48
I think I understand better now.

Does this mean that we'd now need to maintain two separate descriptions of each element? E.g., this CSV-specific documentation, and then the [main documentation](https://github.com/votinginfoproject/vip-specification/blob/vip52/docs/yaml/elements/ballot_measure_contest.yaml)?

Paging @cjerdonek to the discussion.

**Comment by afsmythe** [comment] 2017-01-12 20:57
You're correct @jdmgoogle this option will create two sources of documentation for the two standards (VIP and CSV). I was thinking this option would a temporary solution if it is implemented, since the result will be a single accurate source of information for the states to use to implement 5.1 XML and CSV feeds in the short term. We're hoping to get some momentum with a number of states to convert to 5.1 and are eager to have the documentation materials updated.

**Comment by jdmgoogle** [comment] 2017-01-13 13:51
@afsmythe To clarify, my question isn't around whether there will be separate pages for CSV and XML documentation. My question is whether the documentation update process will look like this:

1. Realize we need to rename "ScopeId" to "JurisdictionId".
2. Update the YAML
3. Run a single python command to output both CSV and XML documentation

or whether it will look like this:

1. Realize we need to rename "ScopeId" to "JurisdictionId".
2. Update the YAML
3. Run a python command to output the XML documentation
4. Update the CSV documentation
5. Run a separate python command to regenerate the CSV documentation

If it's the latter, could you explain why we should go down that path (even in the short term) instead of implementing the steps outlined in [my earlier comment in this thread](https://github.com/votinginfoproject/vip-specification/issues/324#issuecomment-245284619)?

**Comment by afsmythe** [comment] 2017-01-13 20:46
@jdmgoogle existing python commands will build changes to the CSV documentation in to the HTML. No new python will be required for the change I have proposed. When a change to the VIP documentation is required the following tasks will need to be made:

1. Realize a change is needed.
2. Update the YAML (for XML documentation)
3. Update the `csv_template` (for CSV documentation, including the new 'Description')
4. Run the python (`norm_yaml`, `make_rest`) and build the updated documentation with `make html`

I think having a single, true source for both standards is ideal as you have proposed. However, the path I propose should be considered for two reasons:

1. There was uncertainty at the time of your earlier comment about which group (Google, Pew, DW) will implement the code changes you have outlined. A complete list of code changes required is also not identified. 
2. In my review of the current `contributing.md` process, the CSV specific RST files in `*/docs/csv/element_files` are _not_ created/updated by the existing python scripts. These CSV RST files appear to stand on their own. If my review is accurate, I assumed additional python code will need to be made to include the CSV RST files. NOTE: my proposal does require these RST files be updated individually with the `csv-table` directive.

**Comment by jdmgoogle** [comment] 2017-01-24 14:21
@afsmythe I keep seeing "A complete list of code changes hasn't been identified" but when I ask what people think is missing from [this post](https://github.com/votinginfoproject/vip-specification/issues/324#issuecomment-245284619) I've yet to get a good answer. When polled, @cjerdonek seemed to feel the description was relatively complete. What do you feel is missing?

Also I strongly oppose having two separate locations as "the one true source" of correct documentation. If someone is going to go through the effort of writing code to auto-generate CSV-related documentation, that effort should be in furtherance of unifying the documentation, not further codifying a split.

**Comment by jungshadow** [comment] 2017-01-25 15:21
On a separate note from the meat of this conversation, as a documentation reader, I'm a little concerned about using a two-column table for names and descriptions (as mentioned [in this comment](https://github.com/votinginfoproject/vip-specification/issues/324#issuecomment-272207632)). Many of the elements in VIP represent some complex ideas in elections. If the description happens to be lengthy, it could make reading the information difficult, especially on mobile.

I think @cjerdonek made a point once about how the YAML approach was the most flexible if we ever wanted to change the format of the output to something other than tables (which is a good idea...and I take full responsibility for making them tables in the first place).

Circling back to @jdmgoogle's point, I agree that it will make things significantly more error-prone if there are two separate sources for documentation. I've always thought of VIP as one standard with two formats. @afsmythe, couldn't the element and enumeration YAML files contain information about the CSV equivalents much like @jdmgoogle [outlined above](https://github.com/votinginfoproject/vip-specification/issues/324#issuecomment-245284619)?

Cheers.

**Comment by afsmythe** [comment] 2017-01-25 15:42
Thanks for the input everyone. Updating the documentation will get a lot of attention from the states and so arriving at a good solution (that both meets the need and improves the process) is important. My suggestion was intended as a quick, interim solution.

**Comment by afsmythe** [comment] 2017-01-25 15:43
Thanks for input everyone. I'm going to mock up some of the outlined suggestions from @jdmgoogle and @cjerdonek and will ask for more input here as needed.

**Comment by afsmythe** [comment] 2017-02-02 13:30
Hello. I'm digging in to the proposed code changes to include CSV documentation within the YAML and have a question with regards to the splitting of `ELEMENT_COLUMNS` in to CSV and XML sets within [rest.py](https://github.com/votinginfoproject/vip-specification/blob/vip52/scripts/vippy/rest.py). 

Both [get_type_info](https://github.com/votinginfoproject/vip-specification/blob/vip52/scripts/vippy/rest.py#L59) and [make_table_formatter](https://github.com/votinginfoproject/vip-specification/blob/vip52/scripts/vippy/rest.py#L72) use `ELEMENT_COLUMNS`, which `column_infos` assumes the value of. Is the idea here to also expand column_infos in to CSV and XML variables? Pinging @cjerdonek and @jdmgoogle

**Comment by MariaBianchi** [comment] 2017-02-07 20:15
@jdmgoogle or @cjerdonek Do you have any thoughts on the question Franklin posed last week?

**Comment by jdmgoogle** [comment] 2017-02-16 16:19
@afsmythe Yes, I envision updating the get_type_info and make_table_formatter to pass in whether the documentation is in XML or CSV mode, and pass back the correct set of columns based on that.

**Comment by afsmythe** [comment] 2019-01-28 22:11
Just wanted to let everyone know that I'm taking a pass at making the updates [outlined by @jdmgoogle](https://github.com/votinginfoproject/vip-specification/issues/324#issuecomment-245284619). I have a good start on the changes thanks to the clear suggestions there :)

I hope to have something for PR review in the next week or two, but if I run in to any questions I'll be sure to post them here. 

On the VIP side we have run in to some confusion with states implementing the CSV format, particularly around which headers are required for CSV files. I'm excited to have the docs generated from the single YAML files, since it should resolve the confusion and provide a more robust CSV documentation set. Thanks for all the input!

**Comment by afsmythe** [comment] 2019-03-27 17:40
Fixed in https://github.com/votinginfoproject/vip-specification/pull/376

**Closed by afsmythe** 2019-03-27 17:40 UTC
Labels: documentation
